# Sensor toggles
ENABLE_MOTION = True
ENABLE_THERMAL = False
ENABLE_FACE_RECOGNITION = True

# Alert settings
ENABLE_BUZZER = True
ENABLE_LED = True
ENABLE_NOTIFICATIONS = False

# Thresholds
MOTION_SENSITIVITY = 0.5
FACE_RECOGNITION_THRESHOLD = 0.6

# Camera settings
CAMERA_RESOLUTION = (640, 480)


# Telegram settings

TELEGRAM_TOKEN = "8420251258:AAHV8FewCqen5EIgIVUklYnYIdNQZbiJjLk"
TELEGRAM_CHAT_ID = "5303681167"


USE_KNN = False
KNN_NEIGHBORS = 3